# Generated by Django 4.2.20 on 2025-04-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_user_country_code_user_created_at_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
